global:
  scrape_interval: 5s # сбор метрик каждые 5 секунд
  evaluation_interval: 5s # Интервал проверки алертов и записи правил

scrape_configs:
  - job_name: "go-app" # имя приложения
    static_configs:
      - targets: ['host.docker.internal:8087'] # адрес вашего приложения