env: "local"
http_server:
  address: "localhost:8087"
  timeout: 4s
  idle_timeout: 30s
db:
  type: postgres
  host: localhost # postgre-db
  username: postgres
  password: postgres
  port: 5433
  db_name: postgres
  ssl_mode: disable
  max_db_connections: 100
  max_db_idle_connections: 10
  max_db_lifetime: 2h
new_relic:
  app_name: go-app
  license: <NEW_RELIC_LICENSE>
sentry:
  dsn: <SENTRY_DSN>